### ISSUE TITLE
Does this version support KCL 3.X?

### ISSUE THREAD

**Issue by Pola93** [saidsef/aws-kinesis-local#98]
It seems that there is a problem with describing the kinesis stream consumers. The operation ends with 400 bad request

[2024-12-10 10:12:44.341] DEBUG: [id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] WRITE: software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor$StreamedRequest(DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST / HTTP/1.1
Host: localhost:61841
amz-sdk-invocation-id: bcaca70f-155d-e31d-ac71-92a4142aacd9
amz-sdk-request: attempt=1; max=4
Authorization: AWS4-HMAC-SHA256 Credential=dummy/20241210/eu-central-1/kinesis/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=348310056c0b53416d7f0c3714a14bcc9cf5876eb8dcf49f59196e2e7e4b9164
Content-Length: 96
Content-Type: application/x-amz-cbor-1.1
User-Agent: aws-sdk-java/2.28.29 md/io#async md/http#NettyNio ua/2.0 os/Mac_OS_X#15.1.1 lang/java#17.0.10 md/OpenJDK_64-Bit_Server_VM#17.0.10+1-b1087.17 md/vendor#JetBrains_s.r.o. md/en_GB md/scala/2.12.10 md/kotlin/1.9.22-release-704 cfg/retry-mode#legacy cfg/auth-source#stat amazon-kinesis-client-library-java/3.0.1
x-amz-content-sha256: 6e9fdaa67ac154d007a32ba34d1fc71e8718fab789c653074d3aff15cfe1dea3
X-Amz-Date: 20241210T091244Z
X-Amz-Target: Kinesis_20131202.DescribeStreamConsumer) 
{
  "@timestamp": "2024-12-10T10:12:44.341617+01:00",
  "@version": "1",
  "level": "DEBUG",
  "level_value": 10000,
  "logger_name": "io.netty.handler.logging.LoggingHandler",
  "message": "[id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] WRITE: software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor$StreamedRequest(DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)\nPOST / HTTP/1.1\nHost: localhost:61841\namz-sdk-invocation-id: bcaca70f-155d-e31d-ac71-92a4142aacd9\namz-sdk-request: attempt=1; max=4\nAuthorization: AWS4-HMAC-SHA256 Credential=dummy/20241210/eu-central-1/kinesis/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=348310056c0b53416d7f0c3714a14bcc9cf5876eb8dcf49f59196e2e7e4b9164\nContent-Length: 96\nContent-Type: application/x-amz-cbor-1.1\nUser-Agent: aws-sdk-java/2.28.29 md/io#async md/http#NettyNio ua/2.0 os/Mac_OS_X#15.1.1 lang/java#17.0.10 md/OpenJDK_64-Bit_Server_VM#17.0.10+1-b1087.17 md/vendor#JetBrains_s.r.o. md/en_GB md/scala/2.12.10 md/kotlin/1.9.22-release-704 cfg/retry-mode#legacy cfg/auth-source#stat amazon-kinesis-client-library-java/3.0.1\nx-amz-content-sha256: 6e9fdaa67ac154d007a32ba34d1fc71e8718fab789c653074d3aff15cfe1dea3\nX-Amz-Date: 20241210T091244Z\nX-Amz-Target: Kinesis_20131202.DescribeStreamConsumer)",
  "thread_name": "aws-java-sdk-NettyEventLoop-0-4"
}
[2024-12-10 10:12:44.341] DEBUG: [id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] FLUSH 
{
  "@timestamp": "2024-12-10T10:12:44.341749+01:00",
  "@version": "1",
  "level": "DEBUG",
  "level_value": 10000,
  "logger_name": "io.netty.handler.logging.LoggingHandler",
  "message": "[id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] FLUSH",
  "thread_name": "aws-java-sdk-NettyEventLoop-0-4"
}
[2024-12-10 10:12:44.341] DEBUG: [id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] FLUSH 
{
  "@timestamp": "2024-12-10T10:12:44.341834+01:00",
  "@version": "1",
  "level": "DEBUG",
  "level_value": 10000,
  "logger_name": "io.netty.handler.logging.LoggingHandler",
  "message": "[id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] FLUSH",
  "thread_name": "aws-java-sdk-NettyEventLoop-0-4"
}
[2024-12-10 10:12:44.341] DEBUG: [id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] WRITE: DefaultHttpContent(data: UnpooledHeapByteBuf(ridx: 0, widx: 96, cap: 96/96), decoderResult: success), 96B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| bf 69 53 74 72 65 61 6d 41 52 4e 78 39 61 72 6e |.iStreamARNx9arn|
|00000010| 3a 61 77 73 3a 6b 69 6e 65 73 69 73 3a 65 75 2d |:aws:kinesis:eu-|
|00000020| 77 65 73 74 2d 31 3a 30 30 30 30 30 30 30 30 30 |west-1:000000000|
|00000030| 30 30 30 3a 73 74 72 65 61 6d 2f 74 65 73 74 2d |000:stream/test-|
|00000040| 73 74 72 65 61 6d 6c 43 6f 6e 73 75 6d 65 72 4e |streamlConsumerN|
|00000050| 61 6d 65 6b 74 65 73 74 2d 73 74 72 65 61 6d ff |amektest-stream.|
+--------+-------------------------------------------------+----------------+ 
{
  "@timestamp": "2024-12-10T10:12:44.341898+01:00",
  "@version": "1",
  "level": "DEBUG",
  "level_value": 10000,
  "logger_name": "io.netty.handler.logging.LoggingHandler",
  "message": "[id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] WRITE: DefaultHttpContent(data: UnpooledHeapByteBuf(ridx: 0, widx: 96, cap: 96/96), decoderResult: success), 96B\n         +-------------------------------------------------+\n         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |\n+--------+-------------------------------------------------+----------------+\n|00000000| bf 69 53 74 72 65 61 6d 41 52 4e 78 39 61 72 6e |.iStreamARNx9arn|\n|00000010| 3a 61 77 73 3a 6b 69 6e 65 73 69 73 3a 65 75 2d |:aws:kinesis:eu-|\n|00000020| 77 65 73 74 2d 31 3a 30 30 30 30 30 30 30 30 30 |west-1:000000000|\n|00000030| 30 30 30 3a 73 74 72 65 61 6d 2f 74 65 73 74 2d |000:stream/test-|\n|00000040| 73 74 72 65 61 6d 6c 43 6f 6e 73 75 6d 65 72 4e |streamlConsumerN|\n|00000050| 61 6d 65 6b 74 65 73 74 2d 73 74 72 65 61 6d ff |amektest-stream.|\n+--------+-------------------------------------------------+----------------+",
  "thread_name": "aws-java-sdk-NettyEventLoop-0-4"
}
[2024-12-10 10:12:44.341] DEBUG: [id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] FLUSH 
{
  "@timestamp": "2024-12-10T10:12:44.341975+01:00",
  "@version": "1",
  "level": "DEBUG",
  "level_value": 10000,
  "logger_name": "io.netty.handler.logging.LoggingHandler",
  "message": "[id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] FLUSH",
  "thread_name": "aws-java-sdk-NettyEventLoop-0-4"
}
[2024-12-10 10:12:44.342] DEBUG: [id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] WRITE, EmptyLastHttpContent, 0B 
{
  "@timestamp": "2024-12-10T10:12:44.342038+01:00",
  "@version": "1",
  "level": "DEBUG",
  "level_value": 10000,
  "logger_name": "io.netty.handler.logging.LoggingHandler",
  "message": "[id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] WRITE, EmptyLastHttpContent, 0B",
  "thread_name": "aws-java-sdk-NettyEventLoop-0-4"
}
[2024-12-10 10:12:44.342] DEBUG: [id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] FLUSH 
{
  "@timestamp": "2024-12-10T10:12:44.342069+01:00",
  "@version": "1",
  "level": "DEBUG",
  "level_value": 10000,
  "logger_name": "io.netty.handler.logging.LoggingHandler",
  "message": "[id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] FLUSH",
  "thread_name": "aws-java-sdk-NettyEventLoop-0-4"
}
[2024-12-10 10:12:44.345] DEBUG: [id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] READ: DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 400 Bad Request
x-amzn-RequestId: ea650400-b6d6-11ef-a5ce-35c7760d1bd0
x-amz-id-2: 5K+BWDzCN49FfjlAz10vwg42poAHpOFOKA+/QOROKo6Fw3kAISRWh4rzcXEDYr/U+VGpGxY1ACj+7vtUWBHFyZz1XAopRLBI
Content-Type: application/x-amz-cbor-1.1
Content-Length: 35
Date: Tue, 10 Dec 2024 09:12:44 GMT
Connection: keep-alive
Keep-Alive: timeout=5 
{
  "@timestamp": "2024-12-10T10:12:44.345121+01:00",
  "@version": "1",
  "level": "DEBUG",
  "level_value": 10000,
  "logger_name": "io.netty.handler.logging.LoggingHandler",
  "message": "[id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] READ: DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)\nHTTP/1.1 400 Bad Request\nx-amzn-RequestId: ea650400-b6d6-11ef-a5ce-35c7760d1bd0\nx-amz-id-2: 5K+BWDzCN49FfjlAz10vwg42poAHpOFOKA+/QOROKo6Fw3kAISRWh4rzcXEDYr/U+VGpGxY1ACj+7vtUWBHFyZz1XAopRLBI\nContent-Type: application/x-amz-cbor-1.1\nContent-Length: 35\nDate: Tue, 10 Dec 2024 09:12:44 GMT\nConnection: keep-alive\nKeep-Alive: timeout=5",
  "thread_name": "aws-java-sdk-NettyEventLoop-0-4"
}
[2024-12-10 10:12:44.345] DEBUG: [id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] READ: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 35, cap: 35/35, unwrapped: PooledUnsafeDirectByteBuf(ridx: 375, widx: 375, cap: 1024)), decoderResult: success), 35B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| a1 66 5f 5f 74 79 70 65 78 19 55 6e 6b 6e 6f 77 |.f__typex.Unknow|
|00000010| 6e 4f 70 65 72 61 74 69 6f 6e 45 78 63 65 70 74 |nOperationExcept|
|00000020| 69 6f 6e                                        |ion             |
+--------+-------------------------------------------------+----------------+ 
{
  "@timestamp": "2024-12-10T10:12:44.345453+01:00",
  "@version": "1",
  "level": "DEBUG",
  "level_value": 10000,
  "logger_name": "io.netty.handler.logging.LoggingHandler",
  "message": "[id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] READ: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 35, cap: 35/35, unwrapped: PooledUnsafeDirectByteBuf(ridx: 375, widx: 375, cap: 1024)), decoderResult: success), 35B\n         +-------------------------------------------------+\n         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |\n+--------+-------------------------------------------------+----------------+\n|00000000| a1 66 5f 5f 74 79 70 65 78 19 55 6e 6b 6e 6f 77 |.f__typex.Unknow|\n|00000010| 6e 4f 70 65 72 61 74 69 6f 6e 45 78 63 65 70 74 |nOperationExcept|\n|00000020| 69 6f 6e                                        |ion             |\n+--------+-------------------------------------------------+----------------+",
  "thread_name": "aws-java-sdk-NettyEventLoop-0-4"
}
[2024-12-10 10:12:44.345] DEBUG: [id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] READ COMPLETE 
{
  "@timestamp": "2024-12-10T10:12:44.345544+01:00",
  "@version": "1",
  "level": "DEBUG",
  "level_value": 10000,
  "logger_name": "io.netty.handler.logging.LoggingHandler",
  "message": "[id: 0x3b1d5f50, L:/127.0.0.1:61920 - R:localhost/127.0.0.1:61841] READ COMPLETE",
  "thread_name": "aws-java-sdk-NettyEventLoop-0-4"
}
[2024-12-10 10:12:44.346] ERROR: Worker.run caught exception, sleeping for 1000 milli seconds!
software.amazon.awssdk.services.kinesis.model.KinesisException: Service returned error code UnknownOperationException (Service: Kinesis, Status Code: 400, Request ID: ea650400-b6d6-11ef-a5ce-35c7760d1bd0, Extended Request ID: 5K+BWDzCN49FfjlAz10vwg42poAHpOFOKA+/QOROKo6Fw3kAISRWh4rzcXEDYr/U+VGpGxY1ACj+7vtUWBHFyZz1XAopRLBI)
	at software.amazon.awssdk.services.kinesis.model.KinesisException$BuilderImpl.build(KinesisException.java:104)
	at software.amazon.awssdk.services.kinesis.model.KinesisException$BuilderImpl.build(KinesisException.java:58)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.unmarshall(AwsJsonProtocolErrorUnmarshaller.java:92)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:66)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:41)
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:99)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:92)
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:92)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:135)
	at software.amazon.awssdk.core.internal.metrics.BytesReadTrackingPublisher$BytesReadTracker.onComplete(BytesReadTrackingPublisher.java:74)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$DataCountingPublisher$1.onComplete(ResponseHandler.java:519)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:254)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$600(ResponseHandler.java:77)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:375)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.publishMessage(HandlerPublisher.java:402)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.flushBuffer(HandlerPublisher.java:338)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.receivedDemand(HandlerPublisher.java:291)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.access$200(HandlerPublisher.java:61)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:495)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:840) 
{
  "@timestamp": "2024-12-10T10:12:44.346104+01:00",
  "@version": "1",
  "level": "ERROR",
  "level_value": 40000,
  "logger_name": "software.amazon.kinesis.coordinator.Scheduler",
  "message": "Worker.run caught exception, sleeping for 1000 milli seconds!",
  "stack_trace": "software.amazon.awssdk.services.kinesis.model.KinesisException: Service returned error code UnknownOperationException (Service: Kinesis, Status Code: 400, Request ID: ea650400-b6d6-11ef-a5ce-35c7760d1bd0, Extended Request ID: 5K+BWDzCN49FfjlAz10vwg42poAHpOFOKA+/QOROKo6Fw3kAISRWh4rzcXEDYr/U+VGpGxY1ACj+7vtUWBHFyZz1XAopRLBI)\n\tat software.amazon.awssdk.services.kinesis.model.KinesisException$BuilderImpl.build(KinesisException.java:104)\n\tat software.amazon.awssdk.services.kinesis.model.KinesisException$BuilderImpl.build(KinesisException.java:58)\n\tat software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.unmarshall(AwsJsonProtocolErrorUnmarshaller.java:92)\n\tat software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:66)\n\tat software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:41)\n\tat software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52)\n\tat software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:99)\n\tat software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:92)\n\tat software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52)\n\tat software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:92)\n\tat java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)\n\tat software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:135)\n\tat software.amazon.awssdk.core.internal.metrics.BytesReadTrackingPublisher$BytesReadTracker.onComplete(BytesReadTrackingPublisher.java:74)\n\tat software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$DataCountingPublisher$1.onComplete(ResponseHandler.java:519)\n\tat software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:254)\n\tat software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$600(ResponseHandler.java:77)\n\tat software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:375)\n\tat software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.publishMessage(HandlerPublisher.java:402)\n\tat software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.flushBuffer(HandlerPublisher.java:338)\n\tat software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.receivedDemand(HandlerPublisher.java:291)\n\tat software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.access$200(HandlerPublisher.java:61)\n\tat software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:495)\n\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\n",
  "thread_name": "Test worker"
}

**Comment by saidsef** [comment]
Hi @Pola93, according to AWS:
> You can upgrade your stream processing application running on KCL 2.x by simply replacing the current library using KCL 3.0, without any changes in your application code.

Source: https://aws.amazon.com/about-aws/whats-new/2024/11/kinesis-client-library-reduces-stream-processing-compute-costs/

That should be in place replacement.

This is Kinesis lite, it doesn't have all the features, however, you should be able to describe the stream.
